/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.baixing.thrift.moutan;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum AdDraftPostStatus implements org.apache.thrift.TEnum {
  POST_STATUS_NOT_STARTED(-1),
  POST_STATUS_PROCESS(0),
  POST_STATUS_SUCCESS(1),
  POST_STATUS_FAIL(2);

  private final int value;

  private AdDraftPostStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static AdDraftPostStatus findByValue(int value) { 
    switch (value) {
      case -1:
        return POST_STATUS_NOT_STARTED;
      case 0:
        return POST_STATUS_PROCESS;
      case 1:
        return POST_STATUS_SUCCESS;
      case 2:
        return POST_STATUS_FAIL;
      default:
        return null;
    }
  }
}
