/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.baixing.thrift.moutan;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum CollectedStatus implements org.apache.thrift.TEnum {
  STATUS_COLLECTED(0),
  STATUS_ELIMINATED(1),
  STATUS_UNCOLLECTED(-1);

  private final int value;

  private CollectedStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CollectedStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return STATUS_COLLECTED;
      case 1:
        return STATUS_ELIMINATED;
      case -1:
        return STATUS_UNCOLLECTED;
      default:
        return null;
    }
  }
}
