/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.baixing.thrift.moutan;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ErrorCode implements org.apache.thrift.TEnum {
  SYSTEM_ERROR(0),
  SITE_NOT_FOUND(400),
  AD_NOT_FOUND(401),
  USER_NOT_FOUND(402),
  AD_DRAFT_NOT_FOUND(403),
  INVALID_STATUS(404),
  AD_DRAFT_POST_FAIL(405),
  OPERATION_FAIL(406),
  INVALID_MOBILE(407),
  INVALID_CONTENT(408),
  USER_UNSUBSCRIBED(409);

  private final int value;

  private ErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ErrorCode findByValue(int value) { 
    switch (value) {
      case 0:
        return SYSTEM_ERROR;
      case 400:
        return SITE_NOT_FOUND;
      case 401:
        return AD_NOT_FOUND;
      case 402:
        return USER_NOT_FOUND;
      case 403:
        return AD_DRAFT_NOT_FOUND;
      case 404:
        return INVALID_STATUS;
      case 405:
        return AD_DRAFT_POST_FAIL;
      case 406:
        return OPERATION_FAIL;
      case 407:
        return INVALID_MOBILE;
      case 408:
        return INVALID_CONTENT;
      case 409:
        return USER_UNSUBSCRIBED;
      default:
        return null;
    }
  }
}
