/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.baixing.thrift.moutan;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum MoutanSiteStatusType implements org.apache.thrift.TEnum {
  PV(1),
  UV(2),
  NEW_POST(3);

  private final int value;

  private MoutanSiteStatusType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MoutanSiteStatusType findByValue(int value) { 
    switch (value) {
      case 1:
        return PV;
      case 2:
        return UV;
      case 3:
        return NEW_POST;
      default:
        return null;
    }
  }
}
