/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.baixing.thrift.moutan;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum SiteAutoCollectStatus implements org.apache.thrift.TEnum {
  STATUS_DISABLED(0),
  STATUS_ENABLED(1);

  private final int value;

  private SiteAutoCollectStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SiteAutoCollectStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return STATUS_DISABLED;
      case 1:
        return STATUS_ENABLED;
      default:
        return null;
    }
  }
}
