/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.baixing.thrift.moutan;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-06-13")
public class TSiteAdStatus implements org.apache.thrift.TBase<TSiteAdStatus, TSiteAdStatus._Fields>, java.io.Serializable, Cloneable, Comparable<TSiteAdStatus> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TSiteAdStatus");

  private static final org.apache.thrift.protocol.TField COLLECTED_FIELD_DESC = new org.apache.thrift.protocol.TField("collected", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("status", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TSiteAdStatusStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TSiteAdStatusTupleSchemeFactory();

  /**
   * 
   * @see CollectedStatus
   */
  public CollectedStatus collected; // required
  /**
   * 
   * @see SiteAdStatus
   */
  public SiteAdStatus status; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see CollectedStatus
     */
    COLLECTED((short)1, "collected"),
    /**
     * 
     * @see SiteAdStatus
     */
    STATUS((short)2, "status");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // COLLECTED
          return COLLECTED;
        case 2: // STATUS
          return STATUS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.COLLECTED, new org.apache.thrift.meta_data.FieldMetaData("collected", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, CollectedStatus.class)));
    tmpMap.put(_Fields.STATUS, new org.apache.thrift.meta_data.FieldMetaData("status", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, SiteAdStatus.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TSiteAdStatus.class, metaDataMap);
  }

  public TSiteAdStatus() {
  }

  public TSiteAdStatus(
    CollectedStatus collected,
    SiteAdStatus status)
  {
    this();
    this.collected = collected;
    this.status = status;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TSiteAdStatus(TSiteAdStatus other) {
    if (other.isSetCollected()) {
      this.collected = other.collected;
    }
    if (other.isSetStatus()) {
      this.status = other.status;
    }
  }

  public TSiteAdStatus deepCopy() {
    return new TSiteAdStatus(this);
  }

  @Override
  public void clear() {
    this.collected = null;
    this.status = null;
  }

  /**
   * 
   * @see CollectedStatus
   */
  public CollectedStatus getCollected() {
    return this.collected;
  }

  /**
   * 
   * @see CollectedStatus
   */
  public TSiteAdStatus setCollected(CollectedStatus collected) {
    this.collected = collected;
    return this;
  }

  public void unsetCollected() {
    this.collected = null;
  }

  /** Returns true if field collected is set (has been assigned a value) and false otherwise */
  public boolean isSetCollected() {
    return this.collected != null;
  }

  public void setCollectedIsSet(boolean value) {
    if (!value) {
      this.collected = null;
    }
  }

  /**
   * 
   * @see SiteAdStatus
   */
  public SiteAdStatus getStatus() {
    return this.status;
  }

  /**
   * 
   * @see SiteAdStatus
   */
  public TSiteAdStatus setStatus(SiteAdStatus status) {
    this.status = status;
    return this;
  }

  public void unsetStatus() {
    this.status = null;
  }

  /** Returns true if field status is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus() {
    return this.status != null;
  }

  public void setStatusIsSet(boolean value) {
    if (!value) {
      this.status = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case COLLECTED:
      if (value == null) {
        unsetCollected();
      } else {
        setCollected((CollectedStatus)value);
      }
      break;

    case STATUS:
      if (value == null) {
        unsetStatus();
      } else {
        setStatus((SiteAdStatus)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case COLLECTED:
      return getCollected();

    case STATUS:
      return getStatus();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case COLLECTED:
      return isSetCollected();
    case STATUS:
      return isSetStatus();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TSiteAdStatus)
      return this.equals((TSiteAdStatus)that);
    return false;
  }

  public boolean equals(TSiteAdStatus that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_collected = true && this.isSetCollected();
    boolean that_present_collected = true && that.isSetCollected();
    if (this_present_collected || that_present_collected) {
      if (!(this_present_collected && that_present_collected))
        return false;
      if (!this.collected.equals(that.collected))
        return false;
    }

    boolean this_present_status = true && this.isSetStatus();
    boolean that_present_status = true && that.isSetStatus();
    if (this_present_status || that_present_status) {
      if (!(this_present_status && that_present_status))
        return false;
      if (!this.status.equals(that.status))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetCollected()) ? 131071 : 524287);
    if (isSetCollected())
      hashCode = hashCode * 8191 + collected.getValue();

    hashCode = hashCode * 8191 + ((isSetStatus()) ? 131071 : 524287);
    if (isSetStatus())
      hashCode = hashCode * 8191 + status.getValue();

    return hashCode;
  }

  @Override
  public int compareTo(TSiteAdStatus other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetCollected()).compareTo(other.isSetCollected());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCollected()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.collected, other.collected);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetStatus()).compareTo(other.isSetStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status, other.status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TSiteAdStatus(");
    boolean first = true;

    sb.append("collected:");
    if (this.collected == null) {
      sb.append("null");
    } else {
      sb.append(this.collected);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("status:");
    if (this.status == null) {
      sb.append("null");
    } else {
      sb.append(this.status);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (collected == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'collected' was not present! Struct: " + toString());
    }
    if (status == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'status' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TSiteAdStatusStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TSiteAdStatusStandardScheme getScheme() {
      return new TSiteAdStatusStandardScheme();
    }
  }

  private static class TSiteAdStatusStandardScheme extends org.apache.thrift.scheme.StandardScheme<TSiteAdStatus> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TSiteAdStatus struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // COLLECTED
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.collected = com.baixing.thrift.moutan.CollectedStatus.findByValue(iprot.readI32());
              struct.setCollectedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.status = com.baixing.thrift.moutan.SiteAdStatus.findByValue(iprot.readI32());
              struct.setStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TSiteAdStatus struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.collected != null) {
        oprot.writeFieldBegin(COLLECTED_FIELD_DESC);
        oprot.writeI32(struct.collected.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.status != null) {
        oprot.writeFieldBegin(STATUS_FIELD_DESC);
        oprot.writeI32(struct.status.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TSiteAdStatusTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TSiteAdStatusTupleScheme getScheme() {
      return new TSiteAdStatusTupleScheme();
    }
  }

  private static class TSiteAdStatusTupleScheme extends org.apache.thrift.scheme.TupleScheme<TSiteAdStatus> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TSiteAdStatus struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI32(struct.collected.getValue());
      oprot.writeI32(struct.status.getValue());
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TSiteAdStatus struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.collected = com.baixing.thrift.moutan.CollectedStatus.findByValue(iprot.readI32());
      struct.setCollectedIsSet(true);
      struct.status = com.baixing.thrift.moutan.SiteAdStatus.findByValue(iprot.readI32());
      struct.setStatusIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

